<?php

namespace App\Http\Requests\Api\V1\Onboarding;

use Illuminate\Foundation\Http\FormRequest;

/**
 * Admin bootstrap enrolment — only 4 hard-required fields.
 *
 * The admin's only job at this step is to identify the worker:
 *   - full_name
 *   - email          (work email; becomes the worker's login identity)
 *   - date_of_birth  (HR record; the worker can't change this later)
 *   - gender         (HR record)
 *
 * IPPIS ID is auto-generated by the OnboardingController — admins never type it.
 *
 * MDA and verification channel are also captured here because:
 *   - The logged-in admin knows their MDA
 *   - Verification channel is an org-level policy decision, not a worker decision
 *
 * Everything else (department, job title, grade/step, state of posting, LGA,
 * office address, employment date, employment type, NIN/BVN, phone, home
 * address, next of kin, biometrics, bank) is collected during /self-enrol —
 * either by the admin sitting with the worker (kiosk) or by the worker
 * themselves after scanning the QR.
 */
class Step1Request extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'full_name'     => 'required|string|max:255',
            'email'         => 'required|email:rfc|unique:workers,email',
            'date_of_birth' => 'required|date|before_or_equal:' . now()->subYears(18)->toDateString(),
            'gender'        => 'required|in:male,female',

            // MDA is required so the IPPIS counter scopes correctly and verification
            // assignments stay clean. Defaulted to the admin's own MDA on the
            // frontend; super_admins get a dropdown.
            'mda_id'        => 'required|exists:mdas,id',

            // Verification channel is admin policy, not worker preference.
            'verification_channel' => 'required|in:phone,web',

            // Optional bootstrap fields — admin CAN fill these now if they want
            // (kiosk flow), but they're not required at this step. The worker
            // fills them via /self-enrol/{token}/step3 otherwise.
            'department_id'    => 'nullable|exists:departments,id',
            'job_title'        => 'nullable|string|max:255',
            'grade_level'      => 'nullable|integer|between:1,17',
            'step'             => 'nullable|integer|between:1,15',
            'employment_date'  => 'nullable|date|before_or_equal:today',
            'employment_type'  => 'nullable|in:permanent,contract,secondment,casual',
            'state_of_posting' => 'nullable|string',
            'lga'              => 'nullable|string',
            'office_address'   => 'nullable|string',
        ];
    }

    public function messages(): array
    {
        return [
            'email.unique' => 'A worker with this email is already enrolled.',
        ];
    }
}
